version: "3.8"
  services:
    app:
      container_name: Customer
      image: take-care-customer
      build: 
        target: development
      volumes:
        - ./src:/app/src/
      ports:
        - 3000:3000